#!/usr/bin/env groovy
// Liquibase declarative pipeline
//
//
pipeline {
agent any
  environment {
    ENVIRONMENT_STEP="${params.step}"
    TAG="${params.tag}"
    PATH="/path/to/liquibase:$PATH"
  }
  stages {

    stage ('Checkout') {
      steps {
        // checkout Liquibase project from repo
        sh '''
          { set +x; } 2>/dev/null
	  java -version
          git status
          '''
      } // steps for checkout stages
    } // stage 'checkout'

   stage ('liquibase commands'){
      steps {
        sh '''
          { set +x; } 2>/dev/null
          liquibase --version
          echo "------------------------------------"
          echo "----------liquibase status----------"
          echo "------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP status --verbose
          echo "---------------------------------------"
          echo "----------liquibase updateSQL----------"
          echo "---------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP updateSQL
          echo "---------------------------------------------"
          echo "----------liquibase tag database with version1----------"
          echo "---------------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP tag $TAG
          echo "------------------------------------"
          echo "----------liquibase update----------"
          echo "------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP update
          echo "------------------------------------------------------------"
          echo "----------liquibase diff with upper QA environment----------"
          echo "------------------------------------------------------------"
          liquibase --referenceUrl=${URL} --referenceUsername=${USERNAME} --referencePassword=${PASSWORD} --url=$DIFF_URL --username=${DIFF_USERNAME} --password=${DIFF_PASSWORD} --contexts=$ENVIRONMENT_STEP diff
          echo "---------------------------------------------"
          echo "----------liquibase rollback to version1----------"
          echo "---------------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP rollback $TAG
	  echo "------------------------------------"
          echo "----------liquibase update----------"
          echo "------------------------------------"
          liquibase --url=${URL} --username=${USERNAME} --password=${PASSWORD} --contexts=$ENVIRONMENT_STEP update
        '''
      } // steps
    }   // Environment stage

  } // stages
}  // pipeline
