###
### This flowfile is intended to highlight best practices utilizing Liquibase Pro
### Review and update prior to use
###
### Liquibase sales: https://www.liquibase.com/contact
### Liquibase support: https://support.liquibase.com/knowledge
###

### 
### Prior to running the following files must exist in repository:
###
### 1. liquibase.flowfile.yaml
###    This flow file
###    https://docs.liquibase.com/commands/flow/flow.html
###
### 2. liquibase.checks-settings.conf
###    Liquibase quality checks configuration file
###    https://docs.liquibase.com/commands/quality-checks/home.html
###
### 3. changelog.main.xml
###    Root Liquibase changelog file
###    https://docs.liquibase.com/concepts/changelogs/home.html
###

###
### Global variables used in the flowfile
###
globalVariables:
  ###
  ### These variables are typically set via automation tools (see pipeline examples)
  ###
  ### LIQUIBASE_SEARCH_PATH: REQUIRED
  ### Use absolute paths when using Liquibase's Docker container
  ### LIQUIBASE_SEARCH_PATH: "/liquibase/changelog"
  ###
  ### LIQUIBASE_COMMAND_CHANGELOG_FILE: REQUIRED
  ### Root Liquibase changelog file
  ### LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog.main.xml"
  ###
  ### LIQUIBASE_COMMAND_TAG: REQUIRED
  ### Should be a unique identifier e.g. job/build number
  ### LIQUIBASE_COMMAND_TAG: "12345"
  ###
  ### LB_ENVIRONMENT: REQUIRED
  ### LB_ENVIRONMENT should be the environment within the pipeline to operate on (e.g., DEV, UAT, PROD)
  ### LB_ENVIRONMENT: "DEV"
  ###
  ### Secrets: REQUIRED
  ### These values should be pulled from a secure vault via pipeline or Liquibase Pro extension
  ### https://docs.liquibase.com/tools-integrations/extensions/secrets-management/home.html
  ###
  ### LIQUIBASE_COMMAND_URL: "jdbc:h2:tcp://localhost:9090/mem:dev"
  ### LIQUIBASE_COMMAND_USERNAME: "dbuser"
  ### LIQUIBASE_COMMAND_PASSWORD: "letmein"
  ### LIQUIBASE_LICENSE_KEY: "12345"
  ###
  ### Structured logging
  ### Liquibase logs can be ingested by any standard observability tool (e.g., CloudWatch, Datadog, Elastic, Splunk)
  ### https://docs.liquibase.com/tools-integrations/observability/structured-logging.html
  ###
  ### LIQUIBASE_LOG_FILE: "liquibase.log.json"
  ### LIQUIBASE_LOG_FORMAT: "json"
  ### LIQUIBASE_LOG_LEVEL: "WARNING"
  ### LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: "false"
  ###
  ### Other settings
  ### LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: "issues"
  ### LIQUIBASE_SHOW_BANNER: "false"
  ###
  ### Files
  ###
  BASE_DIR: "${LIQUIBASE_SEARCH_PATH}"
  DIFF_FILE: "${BASE_DIR}/Diff_${LB_ENVIRONMENT}.json"
  SNAPSHOT_FILE: "Snapshot_${LB_ENVIRONMENT}.json"
  ###
  ### Reports
  ### Liquibase Pro creates summary reports for certain operations
  ### https://docs.liquibase.com/tools-integrations/observability/operation-reports.html
  ###
  DRIFT_REPORT: "Diff_${LB_ENVIRONMENT}.html"
  UPDATE_REPORT: "Update_${LB_ENVIRONMENT}.html"
  ###
  ### Workflow features
  ### Set these flags to T/F to turn Liquibase Pro features on/off
  LB_TEST_CHECKS: "T"
  LB_TEST_DRIFT: "T"
  LB_TEST_ROLLBACKS: "T"
  ###
  ### LB_CREATE_SNAPSHOT should be set to "F" after the initial pipeline run (future release of Liquibase can determine this at runtime)
  ### Windows - LB_CREATE_SNAPSHOT: "`IF EXIST ${BASE_DIR}/${SNAPSHOT_FILE} (ECHO F) ELSE (ECHO T)`"
  ### Linux - LB_CREATE_SNAPSHOT: "`if [ -f ${BASE_DIR}/${SNAPSHOT_FILE} ]; then echo F ; else echo T ; fi`"
  ###
  LB_CREATE_SNAPSHOT: "T"

###
### Stages to execute
###
stages:
  Default:
    actions:
      #
      # Validate database connection (future)
      #
      # - type: liquibase
      #   command: connect
      #
      # Validate changelog
      #
      - type: liquibase
        command: validate
      #
      # View pending changes
      #
      - type: liquibase
        command: status
        cmdArgs: { verbose: "true" }
      #
      # Show quality checks
      #
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks show
      #
      #
      # Run quality checks
      #
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks run
        cmdArgs: { checks-scope: "changelog, database" }
      #
      # Create initial snapshot
      #
      - type: liquibase
        if: "${LB_CREATE_SNAPSHOT} == T"
        command: snapshot
        globalArgs: { outputfile: "${BASE_DIR}/${SNAPSHOT_FILE}" }
        cmdArgs: { snapshotFormat: "json" }
      #
      # Run diff and check for drift
      # Update database type in cmdArgs (e.g., oracle, mssql, snowflake, etc.)
      #
      - type: liquibase
        if: "${LB_TEST_DRIFT} == T"
        command: diff
        globalArgs: { outputfile: "${DIFF_FILE}" }
        cmdArgs: { drift-severity: "1", report-enabled: "true", report-path: "${BASE_DIR}", report-name: "${DRIFT_REPORT}", referenceURL: "offline:snowflake?snapshot=${SNAPSHOT_FILE}", format: json }
      #
      # Tag the database
      #
      - type: liquibase
        command: tag
        cmdArgs: { tag: "${LIQUIBASE_COMMAND_TAG}" }
      #
      # Review pending changes
      #
      - type: liquibase
        command: updateSQL
      #
      # Update the database
      #
      - type: liquibase
        command: update
        cmdArgs: { report-enabled: "true", report-path: "${BASE_DIR}", report-name: "${UPDATE_REPORT}" }
      #
      # Test rollbacks
      # Typically non-production only
      #
      - type: liquibase
        if: "${LB_TEST_ROLLBACKS} == T"
        command: rollbackSQL
        cmdArgs: { tag: "${LIQUIBASE_COMMAND_TAG}" }
      #
      # Test rollbacks
      # Typically non-production only
      #
      - type: liquibase
        if: "${LB_TEST_ROLLBACKS} == T"
        command: rollback
        cmdArgs: { tag: "${LIQUIBASE_COMMAND_TAG}" }
      #
      # Test rollbacks
      # Typically non-production only
      #
      - type: liquibase
        if: "${LB_TEST_ROLLBACKS} == T"
        command: update
      #
      # Create updated snapshot
      #
      - type: liquibase
        command: snapshot
        globalArgs: { outputfile: "${BASE_DIR}/${SNAPSHOT_FILE}" }
        cmdArgs: { snapshotFormat: "json" }

###
### Always execute
###
endStage:
  actions:
    - type: liquibase
      command: history