--liquibase formatted sql

--changeset SteveZ:15894-createTable_LIBRARY22
CREATE TABLE LIBRARY22 (ID NUMBER(*, 0) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, ACTIVE NUMBER(1, 0) DEFAULT 1, CONSTRAINT PK_SERVICETECH222 PRIMARY KEY (ID));
--rollback drop table LIBRARY22;