--liquibase formatted sql

--changeset SZ:158
CREATE SEQUENCE SALE_SEQUENCE START WITH 21 MAXVALUE 100000;
--rollback drop sequence SALE_SEQUENCE;

--changeset SZ:159
CREATE TABLE SALES (ID NUMBER NOT NULL, ITEM VARCHAR2(50 BYTE) NOT NULL, QUANTITY NUMBER(*, 0) NOT NULL, AMOUNT FLOAT(22) NOT NULL, CONSTRAINT SALES_PK PRIMARY KEY (ID));
--rollback drop table SALES;

--changeset SZ:160
CREATE OR REPLACE TRIGGER "SALE_PRIMARY_KEY_TRG"
   before insert on "SALES"
   for each row
begin
   if inserting then
      if :NEW."ID" is null then
         select SALE_SEQUENCE.nextval into :NEW."ID" from dual;
      end if;
   end if;
end;
/
--rollback drop trigger SALE_PRIMARY_KEY_TRG;

--changeset SZ:161
CREATE TABLE USERS (ID NUMBER NOT NULL, ITEM VARCHAR2(50 BYTE) NOT NULL, QUANTITY NUMBER(*, 0) NOT NULL, AMOUNT FLOAT(22) NOT NULL, CONSTRAINT USERS_PK PRIMARY KEY (ID));
--rollback drop table USERS;

--changeset SZ:162
CREATE TABLE CALLS (ID NUMBER NOT NULL, ITEM VARCHAR2(50 BYTE) NOT NULL, QUANTITY NUMBER(*, 0) NOT NULL, AMOUNT FLOAT(22) NOT NULL, CONSTRAINT CALLS_PK PRIMARY KEY (ID));
--rollback drop table CALLS;
