--liquibase formatted sql

--changeset SZ:250 runwith:sqlplus
CREATE TABLE ACCOUNTS (ID NUMBER NOT NULL, ITEM VARCHAR2(50 BYTE) NOT NULL, QUANTITY NUMBER(*, 0) NOT NULL, AMOUNT FLOAT(22) NOT NULL, CONSTRAINT ACCOUNTS_PK PRIMARY KEY (ID));
--rollback drop table ACCOUNTS;
