--liquibase formatted sql

--changeset SteveZ:15894-createTable_DEPARTMENT
CREATE TABLE DEPARTMENT (ID INT NOT NULL, NAME VARCHAR(50) NOT NULL, ACTIVE BOOLEAN DEFAULT TRUE, CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID));
--rollback drop table DEPARTMENT;