###
### This sample pipeline is intended as a starting point for integration between Liquibase Secure (formerly Liquibase Pro) and Ansible pipelines
### Review and update prior to use
###
### Liquibase version: 5.00.0+
###
### Get Liquibase: https://www.liquibase.com/download-secure
### Liquibase sales: https://www.liquibase.com/contact-us
### Liquibase support: https://support.liquibase.com
### 

### 
### Prior to running the following files must exist in repository:
###
### 1. liquibase.flowfile.yaml
###    Liquibase flow file
###    https://docs.liquibase.com/secure/user-guide-5-0/what-is-a-flow-file
###
### 2. liquibase.checks-settings.conf
###    Liquibase policy checks configuration file
###    https://docs.liquibase.com/secure/user-guide-5-0/use-checks-settings-file
###
### 3. changelog.main.xml
###    Root Liquibase changelog file
###    https://docs.liquibase.com/secure/user-guide-5-0/what-is-a-changelog
###

###
### Ansible documentation: https://docs.ansible.com/
###

---

- name: Running Liquibase
  hosts: localhost
  vars:
    LB_TMP_DIR: /tmp/Toolbox
  tasks:
###
### Checkout repository
### This example uses a personal access token, adjust as required
###
    - name: Checking out repository
      ansible.builtin.git:
        repo: "https://{{ GITHUB_TOKEN }}@github.com/jbennett-liquibase/Toolbox.git"
        dest: "{{ LB_TMP_DIR }}"
 
###
### Ensure ansible user can update files
###
    - name: Updating permissions
      shell: |
        chmod 666 {{ LB_TMP_DIR }}/Diff_*.json
        chmod 666 {{ LB_TMP_DIR }}/Snapshot_*.json

###
### Run the Liquibase flowfile
### Liquibase should be installed where your playbooks run or invoked via Docker
###
    - name: Running Liquibase
      shell: |
        docker run --env LIQUIBASE_SEARCH_PATH=/liquibase/changelog --env LB_BASE_DIR=/liquibase/changelog --env LIQUIBASE_COMMAND_USERNAME --env LIQUIBASE_COMMAND_PASSWORD --env LIQUIBASE_COMMAND_URL --env LIQUIBASE_LICENSE_KEY --env LIQUIBASE_COMMAND_CHANGELOG_FILE --env LB_ENVIRONMENT --rm -v {{ LB_TMP_DIR }}:/liquibase/changelog liquibase/liquibase-secure:latest flow --flow-file=liquibase.flowfile.yaml
      environment:
###
### Set Liquibase environment variables
###
        LB_ENVIRONMENT: DEV
        LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.main.xml
###
### These values should be pulled from pipeline variables or vault
### Secrets should include LIQUIBASE_LICENSE_KEY, LIQUIBASE_COMMAND_USERNAME, LIQUIBASE_COMMAND_PASSWORD, LIQUIBASE_COMMAND_URL
###
        LIQUIBASE_COMMAND_URL: "{{ LIQUIBASE_DEV_URL }}"
        LIQUIBASE_COMMAND_USERNAME: "{{ LIQUIBASE_DEV_USER }}"
        LIQUIBASE_COMMAND_PASSWORD: "{{ LIQUIBASE_DEV_PASSWORD }}"
        LIQUIBASE_LICENSE_KEY: "{{ LIQUIBASE_KEY }}"

###
### Update respository
###
    - name: Updating repository
      shell: |
        cd "{{ LB_TMP_DIR }}"
        git config user.name ansible-user
        git config user.email ansible-users@ansible.com
        git add .
        git commit -m "Update repository"
        git push --force