###
### This sample pipeline is intended as a starting point for integration between Liquibase Pro and Ansible pipelines
### Review and update prior to use
###
### Liquibase version: 4.26.0+
###
### Liquibase sales: https://www.liquibase.com/contact-us
### Liquibase support: https://support.liquibase.com/knowledge
### 

### 
### Prior to running the following files must exist in repository:
###
### 1. liquibase.flowfile.yaml
###    This flow file
###    https://docs.liquibase.com/commands/flow/flow.html
###
### 2. liquibase.checks-settings.conf
###    Liquibase quality checks configuration file
###    https://docs.liquibase.com/commands/quality-checks/home.html
###
### 3. changelog.main.xml
###    Root Liquibase changelog file
###    https://docs.liquibase.com/concepts/changelogs/home.html
###

###
### Ansible documentation: https://docs.ansible.com/
###

---

- name: Running Liquibase
  hosts: localhost
  vars:
    LB_TMP_DIR: /tmp/Toolbox
  tasks:
###
### Checkout repository
### This example uses a personal access token, adjust as required
###
    - name: Checking out repository
      ansible.builtin.git:
        repo: "https://{{ GITHUB_TOKEN }}@github.com/jbennett-liquibase/Toolbox.git"
        dest: "{{ LB_TMP_DIR }}"
 
###
### Ensure ansible user can update files
###
    - name: Updating permissions
      shell: |
        chmod 666 {{ LB_TMP_DIR }}/Diff_*.json
        chmod 666 {{ LB_TMP_DIR }}/Snapshot_*.json

###
### Run the Liquibase flowfile
### Liquibase should be installed where your playbooks run or invoked via Docker
###
    - name: Running Liquibase
      shell: |
        docker run --env LIQUIBASE_SEARCH_PATH=/liquibase/changelog --env LB_BASE_DIR=/liquibase/changelog --env LIQUIBASE_COMMAND_USERNAME --env LIQUIBASE_COMMAND_PASSWORD --env LIQUIBASE_COMMAND_URL --env LIQUIBASE_LICENSE_KEY --env LIQUIBASE_COMMAND_CHANGELOG_FILE --env LIQUIBASE_COMMAND_TAG --env LB_ENVIRONMENT --rm -v {{ LB_TMP_DIR }}:/liquibase/changelog liquibase/liquibase:latest flow --flow-file=liquibase.flowfile.yaml
      environment:
###
### Set Liquibase environment variables
###
        LB_ENVIRONMENT: DEV
        LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.main.xml
        LIQUIBASE_COMMAND_TAG: "{{ ansible_date_time.iso8601_basic }}"
###
### These values should be pulled from pipeline variables or vault
### Secrets should include LIQUIBASE_LICENSE_KEY, LIQUIBASE_COMMAND_USERNAME, LIQUIBASE_COMMAND_PASSWORD, LIQUIBASE_COMMAND_URL
###
        LIQUIBASE_COMMAND_URL: "{{ LIQUIBASE_DEV_URL }}"
        LIQUIBASE_COMMAND_USERNAME: "{{ LIQUIBASE_DEV_USER }}"
        LIQUIBASE_COMMAND_PASSWORD: "{{ LIQUIBASE_DEV_PASSWORD }}"
        LIQUIBASE_LICENSE_KEY: "{{ LIQUIBASE_KEY }}"

###
### Update respository
###
    - name: Updating repository
      shell: |
        cd "{{ LB_TMP_DIR }}"
        git config --global user.name ansible-user
        git config --global user.email ansible-users@ansible.com
        git add .
        git commit -m "Update repository"
        git push --force
