# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'liquibase'

variables:
  appname: MyApp
  version: $(Build.BuildId)

steps:

- script: |
    whoami
    call C:\agent\setupLBDEV.bat > NUL
    echo $(System.DefaultWorkingDirectory)
    call liquibase --version
    call liquibase flow --flow-file=liquibase-checks.flowfile.yaml
  displayName: 'Run Prechecks'

- script: |
    call C:\agent\setupLBDEV.bat > NUL
    call liquibase flow --flow-file=liquibase.flowfile.yaml
  displayName: 'Running Liquibase in DEV environment'

- script: |
    call C:\agent\setupLBDEV_Diff.bat > NUL
    call liquibase diff
  displayName: 'Running quality checks between DEV --> TEST environments'


- script: |
    echo "Zipping Files"
    zip -q -r $(appname)-$(Build.BuildId).zip *
  displayName: 'Zipping Artifact'

- script: |
    mkdir $(System.DefaultWorkingDirectory)\artifacts
    copy "$(appname)-$(Build.BuildId).zip" "$(System.DefaultWorkingDirectory)\artifacts"
  displayName: 'Copy zip to Azure Artifacts'


- upload: $(System.DefaultWorkingDirectory)\artifacts\$(appname)-$(Build.BuildId).zip
  artifact: MyApp
