-- liquibase formatted sql

-- changeset SteveZ:123-1
CREATE TABLE CUSTOMER (ID INT NOT NULL, NAME VARCHAR(50) NOT NULL, AGE INT, LASTNAME VARCHAR(50) NOT NULL, YEAR INT NOT NULL, CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID, YEAR));
-- rollback DROP TABLE CUSTOMER;